CREATE TABLE [dbo].[Persons]
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newId(),
    FirstName NVARCHAR(255) NOT NULL,
    LastName NVARCHAR(255) NOT NULL,
    Birthday DATETIME2 NOT NULL,
    Title NVARCHAR(255) NOT NULL,
    Gender INT NOT NULL,
    Street NVARCHAR(255) NOT NULL,
    [Addition] NVARCHAR(255) NOT NULL,
    Zip int NOT NULL,
    City NVARCHAR(255) NOT NULL,
    PhoneNumber NVARCHAR(40) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    SchoolGraduation DATETIME2 NOT NULL
)