CREATE TABLE [dbo].[Events]
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newId(),
    Host UNIQUEIDENTIFIER NOT NULL, 
    [Name] NCHAR(255) NOT NULL, 
    [Location] NCHAR(255) NOT NULL, 
    [Description] NCHAR(255) NULL, 
    [StartDateTime] DATETIME2 NOT NULL, 
    [EndDateTime] DATETIME2 NOT NULL, 
    [PictureId] UNIQUEIDENTIFIER NULL
    CONSTRAINT FK_PictureId FOREIGN KEY (PictureId) REFERENCES Files(Id) ON DELETE CASCADE ON UPDATE CASCADE, 
    [IsPublic] BIT NOT NULL DEFAULT 0
)