CREATE TABLE [dbo].[Events]
(
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newId(),
    Host UNIQUEIDENTIFIER NOT NULL, 
    [Name] NVARCHAR(255) NOT NULL, 
    [Location] NVARCHAR(255) NOT NULL, 
    [Description] NVARCHAR(255) NULL, 
    [StartDateTime] DATETIME2 NOT NULL, 
    [EndDateTime] DATETIME2 NOT NULL, 
    [PictureId] UNIQUEIDENTIFIER NULL
    CONSTRAINT FK_PictureId FOREIGN KEY (PictureId) REFERENCES Files(Id), 
    [IsPublic] BIT NOT NULL DEFAULT 0
)