CREATE TABLE [dbo].[Files] 
(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT newId(), 
    [FileName] NVARCHAR(255) NULL, 
    [FileType] NVARCHAR(255) NULL, 
    [FileContentId] UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_FileContentId FOREIGN KEY (FileContentId) REFERENCES FileContent(Id) ON DELETE CASCADE
)
