name: Gated Committee

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies (Server)
        run: dotnet restore Server/Functions.Server.csproj

      - name: Restore Dependencies (Client)
        run: dotnet restore Client/Functions.Client.csproj

      - name: Build Server
        run: dotnet build Server/Functions.Server.csproj --configuration Release --no-restore

      - name: Build Client
        run: dotnet build Client/Functions.Client.csproj --configuration Release --no-restore
